[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
name = "preassets"
version = "0.1.0"

[dependencies]
bdf = "0.5.5"
image = "0.23.12"
shaderc = "0.6.1"
