[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
name = "renderer"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = "1.4.0"
libremexre = "0.1.12"
vulkano = "0.14.0"
vulkano-win = "0.14.0"
winit = "0.19.3"
