[package]
name = "renderer"
version = "0.1.0"
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"

[lib]
name = "renderer"
crate-type = ["dylib"]

[dependencies]
derivative = "1.0.3"
libremexre = "0.1.12"
vulkano = "0.14.0"
vulkano-win = "0.14.0"
winit = "0.19.3"
